### ISSUE TITLE
[DOC] what is the expected output type for the Jacobian?

### ISSUE THREAD

**Issue by Datseris** [rveltz/BifurcationKit.jl#21]
Hi there,

I'm trying to come up with a simple example for the bifurcation of 1-dimensional system to contribute to the documentation, under guidance of @gszep . I have the example running, by altering the code https://rveltz.github.io/BifurcationKit.jl/dev/iterator/#  , but there are some things that are not yet clear enough for me.

What I really want to know is **what is the allowed return types** for both the vector field `f` and the Jacobian. The code has:
```
Jac_m = (x, p) -> diagm(0 => 1.0  .- x.^k)
```
but it was confusing for me because when I tried other types of `Jac_m` I got errors (I am not reporting errors here until I first see what is the expected form of Jacobian). I also tried to use the output of `ForwardDiff.jacobian`, also getting errors.

So, can you please document somewhere centrally in the documentation what is the expected forms for `f, J`? Not only what are the input arguments, but what is the expected output. The documentation of e.g. https://rveltz.github.io/BifurcationKit.jl/dev/library/#BifurcationKit.continuation does not discuss with clarity what `J` should be. There you can also provide tips and tricks, as e.g. the above usage of `diagm` is definitely something advanced for me, I would expected a 1-element matrix as return type in this example.

---

A comment on how the docstring is structured: it provides:

```julia
F = (x, p) -> F(x, p)
```
This, almost always, is invalid Julia code. If `F` is an existing function, here you are redefining it as an anonymous function `F`, and Julia will just error. It also doesn't highlight what is the return type of `F`, yet repeats what are the expected input arguments.

Why not consider replacing it with the more valid `F(x,p)::AbstractVector`, or simply explicitly write things out as e.g. "`F` is a function with input arguments `(x, p)` returning a vector `r` that represents the vector field of the dynamics".

---

Are static vectors supported?

**Comment by rveltz** [comment]
Hi,

For `F`, it is like you said.  "F is a function with input arguments (x, p) returning a vector r that represents the vector field of the dynamics and for type stability, the types of x and r should match".

For the jacobian `J`, it should be a function `J(x,p)` which returns a function taking one argument `dx` and returns `dr` of the same type of `dx`. It just happens that when `J(x,p)` returns a matrix,  you can use it like `J(x,p)(dx)` and so the above works.

> When `J(x,p)` is a fancy function, you can pass your own linear solver if you have a better one for your problem.

---

```
Jac_m = (x, p) -> diagm(0 => 1.0  .- x.^k)
```
This iterator docs, uses the above definition for the jacobian. It returns a diagonal matrix, as explained above.

For the use or ForwardDiff, please check the [docs](https://rveltz.github.io/BifurcationKit.jl/dev/search/?q=forwarddiff) online, it has been used many times in the tutorials either in the matrix way or functions.

---

For static vectors, I have not tried and it is unlikely to work I would guess. For example, this [line](https://github.com/rveltz/BifurcationKit.jl/blob/master/src/Newton.jl#L116) would break. This could be corrected by specializing the methods [BorderedArrays.jl](https://github.com/rveltz/BifurcationKit.jl/blob/master/src/BorderedArrays.jl) of to static arrays.

---

I will modify the docs with your suggestions. Thank you for opening this issue.

**Comment by rveltz** [comment]
Coming back to this. Can't you do something along the lines of:

```
const Jnew = 1 #put something meaningdfull

res = newton(F, (x,p) -> (jacobian!(Jnew, x, p, 0); Jnew), ...)
```

**Comment by Datseris** [comment]
Indeed! Since I anyways have to make a transformation to drop the `t` argument, then I can do this directly.

**Comment by rveltz** [comment]
Can we close this issue?

**Comment by Datseris** [comment]
Yeap! If I have other doc questions or suggestions I'll open new issues!

**Comment by rveltz** [comment]
👍
