### ISSUE TITLE
Exchange Plots dependency with Requires...?

### ISSUE THREAD

**Issue by Datseris** [rveltz/BifurcationKit.jl#26]
When BifurcationKit is installed, the whole Plots library and GR (whose combination is massive) is installed with it.

Perhaps a more lean approach would be to use the Requries package and add conditional dependencies, so that users don't have to get Plots if they don't want to plot things? For example, have a look of how I have done this in DynamicalBilliards.jl, which extends several PyPlot.jl functions:

https://github.com/JuliaDynamics/DynamicalBilliards.jl/blob/master/src/DynamicalBilliards.jl#L51-L63

**Comment by rveltz** [comment]
You are right. Actually, I only need `RecipesBase`. The only part I am concerned with is this [one](https://github.com/rveltz/BifurcationKit.jl/blob/master/src/Plotting.jl#L106) where I used `Plots.@layout`. However the test dont use it so it should be fine.

I will try to remove Plots from the deps if that solves your issue.

**Comment by rveltz** [comment]
It is done on master. Feel free to close the issue.
