### ISSUE TITLE
dz = norm(z[n+1]-z[n]) along branch from branch.ds?

### ISSUE THREAD

**Issue by gszep** [rveltz/BifurcationKit.jl#29]
Since I am doing a line integral over the steady states returned by continuation I need a precise `ds`. I believe the `ds` given in `branch.ds` is the target `ds` between `dsmin` and `dsmax` that an adaptive time stepping regime aims for? Took me a while to realise I was not getting the correct `ds` :sweat_smile:

**Comment by rveltz** [comment]
There is no `ds` in `branch.sol` where `branch::ContResult`. You can access the list of ds using `branch.ds`

```julia
julia> branch.sol[1] |> keys
(:x, :p, :step)
```

I am not sure I understand you correctly

**Comment by gszep** [comment]
sorry correction what I meant to say was `branch.ds`

**Comment by gszep** [comment]
I guess what I want is `dz = norm(z[n+1]-z[n])`

**Comment by rveltz** [comment]
> sorry correction what I meant to say was branch.ds I thought ds was the arc-length step?

Yes. Why is it wrong?

> dp = ds only for the first step of the algorithm?

It depends, there is a newton correction that seeks (x,p) as funtion of `ds`  


This is explained [here](https://rveltz.github.io/BifurcationKit.jl/dev/library/#Continuation-1), scroll down to the algorithm section

**Comment by gszep** [comment]
ok so if I want to calculate the line integral 
![image](https://user-images.githubusercontent.com/17977117/100736594-485b6f80-33d3-11eb-8b79-996658db2d15.png)
where `gamma(s)` is an arclength parametrisation of my steady state branch, how do I calculate the proper line element
![image](https://user-images.githubusercontent.com/17977117/100736827-97090980-33d3-11eb-89d1-77fc1aa8badc.png)
using existing results in `branch::ContResult`

**Comment by rveltz** [comment]
Each point is parametrised by `s = cumsum(branch.ds)`. You need the tangent but I dont save it...If you use an iterator, you can save it yourself?

**Comment by gszep** [comment]
to clarify, is the tangent in your code `tau`?

**Comment by rveltz** [comment]
yes

**Comment by gszep** [comment]
great! so the solution I was looking involves
```julia
iterator = ContIterable( (u,p)->F(u,p,θ), J, u, p, (@lens _), options )

for state ∈ iterator
	push!( solutions, ( z = solution(state), dz = state.tau*state.ds )
end
```
I will close this issue now
