### ISSUE TITLE
Docs missing description of what verbosity levels does (?)

### ISSUE THREAD

**Issue by TorkelE** [rveltz/BifurcationKit.jl#32]
A quick thing. Doesn't matter much but realised that it seemed like this was missing, so figured I'd add it here.

Various methods have an option `verbosity`, which can carry between `0` and `3` (or `5`). However, nowhere does it seem to say exactly what these various levels actually do. testing various things mostly solves it, but could possibly be useful to add in the docs some day (although not of high priority).

**Comment by rveltz** [comment]
I guess 

> verbosity::Int controls the amount of information printed during the continuation process. Must belong to {0,1,2,3}

is not enough. I make it more precise

**Comment by TorkelE** [comment]
It is helpful, and I could test the options to see what comes out. More would be helpful but not necessary. Whenever you add more to the docs it might be a thing to keep in mind though.

**Comment by rveltz** [comment]
This should be addressed by [commit](https://github.com/rveltz/BifurcationKit.jl/commit/c63f744f381c0b624be620a0b7519af1f74d2df0). I am closing it ffor now, feel free to reopen it if you are not satisfied.
