### ISSUE TITLE
Unable to create bifurcation diagram using deflated continuations

### ISSUE THREAD

**Issue by TorkelE** [rveltz/BifurcationKit.jl#33]
First, sorry for all the troubles!

I have been trying to create some very simple bifurcation diagrams using deflated continuations; however, I have not been able to get it to work. I think I simply do not understand how to give some of the input properly.

The first example is a very simple system:
dX/dt = p -d*X (p and d are parameters)
I create the system using Catalyst. 

For reference, I have been using the deflated continuation example at https://rveltz.github.io/BifurcationKit.jl/dev/DeflatedContinuation/, as well as the `@reaction_network` example discussion at https://github.com/rveltz/BifurcationKit.jl/issues/27.

In my first try, I simply take the example in the docs, but swaps stuff out for what I got in my system:
```julia
# Fetch packages.
using Catalyst
using BifurcationKit, LinearAlgebra, Setfield, SparseArrays, Plots

# Create functions.
rn = @reaction_network begin
    p, 0 --> X
    d, X --> 0
end p d;
odefun = ODEFunction(convert(ODESystem,rn),jac=true)
F = (u,p) -> odefun(u,p,0)
J = (u,p) -> odefun.jac(u,p,0);

# Set initial parameter values.
p = (p=1.,d=0.1);
# Sets initial guess
x0 = 0.5;

# Set solving options
opts = BifurcationKit.ContinuationPar(dsmax = 0.051, dsmin = 1e-3, ds=0.001, maxSteps = 140, pMin = -3., saveSolEveryStep = 0, newtonOptions = NewtonPar(tol = 1e-8, verbose = false), saveEigenvectors = false);

# Set Deflation Options
DO = DeflationOperator(2.0, dot, .001, [[0.]]);

# Create bifurcation diagram
brdc, = continuation(F,J, x0, (@lens _),opts,DO; showplot=false, verbosity = 0);

# Plot the diagram
plot(brdc[1])
```
This code runs without error, but the output is weird, and rightly so, since the algorithm doesn't have the adequate information. It is when I move on from this I start to be confussed. First, I have a question regarding the creation of the `DeflationOperator` though:
-  If I understand it right, argument 1 and 3 are simple parameters to the algorithm (knowing little about appropriate values, I simply selected what was used in the example). The second argument is a function (is there any reason I would not use `dot`?). Finally, the fourth argument is an array with roots which I want to avoid? Exactly how should I give it here? Is it roots which I want to ignore, or is it to help the algorithm to find all the roots at the starting condition, but do I then need to give all of the roots except for one (with the algorithm finding the last one)? In the doc example, a root at 0 is given, but the algorithm finds and uses 2 more. If I don't want to skip any roots, can I give this one as an empty array?

Next, I try to give the systems parameter values as an input as well, I try a few different ones, the only one that succeeds is:
```julia
brdc, = continuation(F,J,p, (@lens _.p),opts,DO; showplot=false, verbosity = 0);
```
- However, I am unsure why I should, when providing a parameter, no longer provide `x0`? Other alternatives such as:
```julia
brdc, = continuation(F,J,x0, p, (@lens _.p),opts,DO; showplot=false, verbosity = 0);
brdc, = continuation(F,J,p, x0, (@lens _.p),opts,DO; showplot=false, verbosity = 0);
```
   fails

Next, I try a slightly more complicated system:
```julia
# Fetch packages.
using Catalyst
using BifurcationKit, LinearAlgebra, Setfield, SparseArrays, Plots

# Create functions.
rn2 = @reaction_network begin
    (v0+(S*X)^n/((S*X)^n+(D*A)^n+1),1), ∅ ↔ X
    (τ*X,τ), ∅ ↔ A
end v0 S n D τ;
odefun2 = ODEFunction(convert(ODESystem,rn2),jac=true)
F2 = (u,p) -> odefun2(u,p,0)
J2 = (u,p) -> odefun2.jac(u,p,0);

# Set initial parameter values.
p2 = (v0=0.1, S=1., n=3, D=2., τ=0.01);
# Sets initial guess
x02 = [0.5, 0.5];

# Set solving options
opts2 = BifurcationKit.ContinuationPar(dsmax = 0.051, dsmin = 1e-3, ds=0.001, maxSteps = 1000000, pMin = 0.1, pMax = 5., saveSolEveryStep = 0, newtonOptions = NewtonPar(tol = 1e-8, verbose = false), saveEigenvectors = false);

# Set Deflation Options
DO2 = DeflationOperator(2.0, dot, .001, [[0.,0.]]);

# Create bifurcation diagram
brdc2, = continuation(F2,J2,p2, (@lens _.S),opts2,DO2; showplot=false, verbosity = 0);

# Plot the diagram
plot(brdc2[1])
```
This does give me parts of the diagram as output, but not everything (it is one of those bistable switches, but I only get the first third, up until it is supposed to turn over and go backwards):
![bad_bif](https://user-images.githubusercontent.com/18099310/104205886-d2f9aa80-5426-11eb-8a4b-29437f29f312.png)

I have tried modifying option values, as well as adding
```julia
termination_condition(x, f, J, residual, iteration, niter, options; kwargs...) = residual <1e3
root_search(x,p,id) = x .+ rand(length(x))
```
but didn't get it to work. What is going wrong here, and what should I do to modify?

**Comment by rveltz** [comment]
There are many mistakes. The first is tied to the confusion of calling everybody `p`. You should do `par = (p=1.,d=0.1)`. Then you have to decide the parameter for the continuation. Let us say, that we chose `p`, we then give the lens `@lens _.p`.

Finally, if you look at the docs of deflated continuation, you will see:

> defOp::DeflationOperator a Deflation Operator (see DeflationOperator) which contains the set of
       solution guesses for the parameter par.

Hence, `DO` contains all the initial guesses (there can be many). Also, note that `pMax=1` so nothing will be done. Hence:

```julia
# Set initial parameter values.
par = (p=1.,d=0.1);
# Sets initial guess
x0 = 0.5;

# Set solving options
opts = BifurcationKit.ContinuationPar(dsmax = 0.051, dsmin = 1e-3, ds=0.001, maxSteps = 140, pMin = -3., saveSolEveryStep = 0, newtonOptions = NewtonPar(tol = 1e-8, verbose = false), saveEigenvectors = false, pMax = 3.);

# Set Deflation Options
DO = DeflationOperator(2.0, dot, .001, [[0.]]);

# Create bifurcation diagram
brdc, = continuation(F,J,par, (@lens _.p),opts,DO; showplot=false, verbosity = 0);

# Plot the diagram
plot(brdc...)
```

**Comment by rveltz** [comment]
This should put you on track for the second part.

**Comment by TorkelE** [comment]
Thank you! Yeah, having two things called `p` seems like a terrible idea, totally missed that.

I think I understand regarding the `x0` then, basically because it is provided in the `DeflationOperation` it is not required separately? Checking the documentation again, it seems that `x0` is absent from the `continuation` arguments when `DeflationOperation` is present. 

I can get it works well for the first example now, but I still cannot get it to work in the second one:
```julia
# Fetch packages.
using Catalyst
using BifurcationKit, LinearAlgebra, Setfield, SparseArrays, Plots

# Create functions.
rn2 = @reaction_network begin
    (v0+(S*X)^n/((S*X)^n+(D*A)^n+1),1), ∅ ↔ X
    (τ*X,τ), ∅ ↔ A
end v0 S n D τ;
odefun2 = ODEFunction(convert(ODESystem,rn2),jac=true)
F2 = (u,p) -> odefun2(u,p,0)
J2 = (u,p) -> odefun2.jac(u,p,0);

# Set initial parameter values.
par2 = (v0=0.1, S=1., n=3, D=2., τ=0.01);
# Sets initial guess
x02 = [0.5, 0.5];

# Set solving options
opts2 = BifurcationKit.ContinuationPar(dsmax = 0.051, dsmin = 1e-3, ds=0.001, maxSteps = 1000000, pMin = 0.1, pMax = 5., saveSolEveryStep = 0, newtonOptions = NewtonPar(tol = 1e-8, verbose = false), saveEigenvectors = false);

# Set Deflation Options
DO2 = DeflationOperator(2.0, dot, .001, [[0.10102148057306666,0.10102148057306666]]);


# Create bifurcation diagram
brdc2, = continuation(F2,J2,par2, (@lens _.S),opts2,DO2; showplot=false, verbosity = 0);

# Plot the diagram
plot(brdc2[1])
```
Here there is no naming conflict, and `pMax=5.` should be good. I have also set the `DeflationOperator properly, at `DO2 = DeflationOperator(2.0, dot, .001, [[0.10102148057306666,0.10102148057306666]]);`. Here `[0.10102148057306666,0.10102148057306666]` is the (single) fixed point of the system at the initial condition of the parameter set. The lens should also properly point towards the parameter `S`.

**Comment by rveltz** [comment]
> Checking the documentation again, it seems that x0 is absent from the continuation arguments when DeflationOperation is present.

Exactly. I could put DO at the place of x0 but dispatching would be less happy then.

For the second part, something is off.

```
brdc3, = continuation(F2,J2,[0.10102148057306666,0.10102148057306666],par2, (@lens _.S),opts2;  verbosity = 0, plot=true);
```

**Comment by rveltz** [comment]
> Note that you dont need to use [0.10102148057306666,0.10102148057306666] for your guess, it will be improved anyway. You can pass `zeros(2)`.


OK, I got it to work. It requires some tuning because newton is too good for your system, so it is good to limit `maxIter` in `newton`. First, you cannot find new branches because you don't perturb your solution. So you should do the following.

```
opts2 = BifurcationKit.ContinuationPar(dsmax = 0.051, dsmin = 1e-3, ds=0.001, maxSteps = 1000000, pMin = 0.1, pMax = 5., saveSolEveryStep = 0, newtonOptions = NewtonPar(tol = 1e-9, verbose = false, maxIter = 15), saveEigenvectors = false);

brdc2, = continuation(F2,J2,par2, (@lens _.S),opts2,DO2;
    showplot=false, verbosity = 0,
    perturbSolution = (x,p,id) -> (x  .+ 0.8 .* rand(length(x))),
    )
```

but then you get in the unpleasant situation where newton find the same solutions which are deflated (you will see a lot of `┌ Error: Same solution found for identical parameter value!!`). It is indeed possible because the deflation operator is 1/(alpha + |x-x0|) and alpha>0. The theoritical case is alpha = 0. However, you can limit this behavior by restricting the size of the residual:

```
brdc2, = continuation(F2,J2,par2, (@lens _.S),opts2,DO2;
    showplot=false, verbosity = 0,
    tangentAlgo = SecantPred(),
    perturbSolution = (x,p,id) -> (x  .+ 0.8 .* rand(length(x))),
    callbackN = (x, f, J, res, iteration, itlinear, options; kwargs...) -> res <1e7
    )
```

All in all, I use:

```julia
# Set solving options
opts2 = BifurcationKit.ContinuationPar(dsmax = 0.051, dsmin = 1e-3, ds=0.001, maxSteps = 1000000, pMin = 0.1, pMax = 5., saveSolEveryStep = 0, newtonOptions = NewtonPar(tol = 1e-9, verbose = false, maxIter = 15), saveEigenvectors = false);

# Set Deflation Options
DO2 = DeflationOperator(2.0, dot, 1., [[0.0,0.0]]);

# Create bifurcation diagram
brdc2, = continuation(F2,J2,par2, (@lens _.S),opts2,DO2;
    showplot=false, verbosity = 0,
    tangentAlgo = SecantPred(),
    perturbSolution = (x,p,id) -> (x  .+ 0.8 .* rand(length(x))),
    callbackN = (x, f, J, res, iteration, itlinear, options; kwargs...) -> res <1e7
    )

# Plot the diagram
plot(brdc2...)
```

and get 

![Screen Shot 2021-01-12 at 10 08 31](https://user-images.githubusercontent.com/1591812/104293273-20752680-54be-11eb-84a6-bb796638c708.png)

> In the next version of BK, the branches will be automatically merged so it would return 2 branches in the above case.

I still find it tough to find generic parameters. For PDE, the currrent setting is not too bad, I use it for > 2e7 unknowns on the GPU. But for ODE, I notice that you have to limit `newton` which despite the deflation is sometimes able to find the same roots because it can assume large residuals. Although, on the GPU, I limit the residuals as well. So perhaps it would be a good idea to limit the residuals altogether and the user can override this if it is too limiting.

Hope this helps.

**Comment by TorkelE** [comment]
Yes, that really helped, I get it to work now.

A few last (not sure who I am kidding, will probably be back here more times) questions:

- In some cases, the algorithm would be able to connect the branches (e.g. my second set of code in https://github.com/rveltz/BifurcationKit.jl/issues/27). If I understand you right, is it simply that the algorithm for connecting branches isn't implemented for deflated continuations (but will be in the next update)?
- If I add the ` detectBifurcation=3` option to the `ContinuationPar`, it doesn't find the last fold point, is there a way to find that one as well?
![fold_bp_not_found](https://user-images.githubusercontent.com/18099310/104307990-dc871f00-54c7-11eb-9272-8ddd76b19e48.png)

- In addition to the three lines forming something like an "S", there's a fourth line (red in yours and green in mine), sloping downwards from left to right. What _exactly_ is this line? It corresponds to no fixed point of the system. Unless it comes from some kind of solution with positive/negative values. Checking values along that path, both variables seem to have negative values?

**Comment by rveltz** [comment]
>  is it simply that the algorithm for connecting branches isn't implemented for deflated continuations (but will be in the next update)?

It is implemented. I am tested it before releasing.

> If I add the detectBifurcation=3 option to the ContinuationPar, it doesn't find the last fold point, is there a way to find that one as well?

Note that detectBif=3 is not implemented with DC for now. 
Also, DC cannot find Fold points.

> Checking values along that path, both variables seem to have negative values?
I leave this to you

**Comment by TorkelE** [comment]
I understand, thanks for all the help!

**Comment by rveltz** [comment]
No prob.

**Comment by TorkelE** [comment]
I got the third one now as well.
(for further reference, there's a `printSolution` argument  in `continuation()` with a default value of `(x, p) -> norm(x)`. Setting this to`(x, p) -> x[1]` gets the in this case desired output, the value of the first varraible of the system at the bifurcation point)

**Comment by rveltz** [comment]
the third?

**Comment by TorkelE** [comment]
Sorry, the third of my questions in the last set:

- In addition to the three lines forming something like an "S", there's a fourth line (red in yours and green in mine), sloping downwards from left to right. What exactly is this line? It corresponds to no fixed point of the system. Unless it comes from some kind of solution with positive/negative values. Checking values along that path, both variables seem to have negative values?

**Comment by rveltz** [comment]
I dont know. It should be a valid solution to your equations. You can reject it using a callback function based on `sign` in `newton` and it will not be considered by `BifurcationKit`
