### ISSUE TITLE
`dTMvf` is an undefined name in the Neural mass equation example

### ISSUE THREAD

**Issue by Datseris** [rveltz/BifurcationKit.jl#34]
https://rveltz.github.io/BifurcationKit.jl/dev/tutorialsODE/#Neural-mass-equation-(automatic)-1 

In the first code block the variable `dTMvf` is used but nowhere defined so I couldn't run the example.

Going into the source of the of the doc page I saw that all documentation code blocks are just markdown `julia` blocks. Why is it that they are not documenter `@example` blocks? Documenter makes it extremely easy to just run code and put its output at the end. This include figures. Simply return the value of `plot(br, plotfold=false, markersize=3, legend=:topleft)` and it will be displayed. 

If the docs are built via running code, this kindof guarantees that the examples are correct and also do what is expected. Furthermore, you do not have to update the output codeblocks, nor figures, if you want to update the example. It happens automatically.

**Comment by Datseris** [comment]
Oddly, in the examples folder https://github.com/rveltz/BifurcationKit.jl/blob/master/examples/TMModel.jl it is defined 
```julia
dTMvf = (z,p) -> ForwardDiff.jacobian(x-> TMvf(x,p), z)
```

**Comment by rveltz** [comment]
You are right, I should use `@example` for the ODE examples, they are fast to run. I will correct the mistake today and update to `@example` when I have more time.

Thank you for spotting this

**Comment by rveltz** [comment]
It should be fixed. Should we close this?

**Comment by Datseris** [comment]
It's up to you. The example still doesn't use documenter syntax. If you want an issue to remind you of that leave it open, otherwise you can close!
