### ISSUE TITLE
Continuation function misses negative branch of saddle-node bifurcation?

### ISSUE THREAD

**Issue by zornsllama** [rveltz/BifurcationKit.jl#35]
I may be misunderstanding something, but it seems that the continuation function is saving incorrect equilibrium values to the ContResult object. In particular, I was looking at the following example.

```
using ForwardDiff, Parameters, Setfield, Plots, LinearAlgebra, SparseArrays
using BifurcationKit
const BK = BifurcationKit

F(x,p) = @. (x^2 - p)
JacF(x,p) = spdiagm(0=> 2. .* x)

opts = ContinuationPar(detectBifurcation = 3, dsmax = 0.1, dsmin = 1e-3, ds = -0.001, maxSteps = 130, pMin = -3., pMax = 1., saveSolEveryStep = 0, newtonOptions = NewtonPar(tol = 1e-8, verbose = true));

iter = BK.ContIterable(F, JacF, [-0.9], 1., (@lens _), opts; verbosity = 2);
```

If I run `continuation!(iter)`, the resulting branch covers the positive equilibria (sqrt(p)) twice and misses the negative equilibria (-sqrt(p)) (despite passing a negative initial condition). In contrast, if I iterate the ContInterable by hand, then PALC correctly identifies both positive and negative equilibria.

```
res = ContResult(iter, iterate(iter)[1])
resx = Float64[]

st = iterate(iter)

while st[1] != nothing
    push!(resx, getx(st[1])[1])
    BK.save!(res, iter, st[1])
    st = iterate(iter, st[1])
end

```

Now if I examine the res.x  and compare with the resx list, the resx list contains the negative equilibria but res.x contains the positive equilibria twice.

Am I missing something here, or is this a bug? Thanks!

**Comment by zornsllama** [comment]
Ah, the default printSolution function is norm! Hopefully anyone in the future having this issue can benefit from my confusion.

**Comment by rveltz** [comment]
You maybe have been tricked by my wrong choice of name function. In `continuation`, the keyword argument `printSolution` is a function used to actually save information about the solution because in the large scale problems, it is too costly to save the solution at each iterate.

Perhaps it should be called `saveInfofromSol`. If you have a suggestion...

**Comment by zornsllama** [comment]
Maybe `recordFromSol'? I certainly wouldn't be opposed to `saveInfoFromSol` either though.

**Comment by rveltz** [comment]
why not. Thanks.
