### ISSUE TITLE
AssertionError message in ContinuationPar might be incorrect 

### ISSUE THREAD

**Issue by rseydam** [rveltz/BifurcationKit.jl#39]
Hey,

Maybe I am mistaken but I believe an AssertionError message in ContinuationPar() is off.
When given an odd number for nInversion it raises the error: The option `nInversion` number must be odd. 

@assert iseven(nInversion) "The option `nInversion` number must be odd"

Should the number of inversions be even or odd?

**Comment by rveltz** [comment]
Well spotted! It should be even

**Comment by rveltz** [comment]
It is addressed in this [commit](https://github.com/rveltz/BifurcationKit.jl/commit/0f852631602992a243460ccca3d553dd34b1f812). Thank you for reporting.
