### ISSUE TITLE
Computing bifurcation diagrams or branch points with only the first derivative

### ISSUE THREAD

**Issue by TorkelE** [rveltz/BifurcationKit.jl#46]
Hello,
I have a 2 variable ODE system for which I want to computer a bifurcation diagram. I managed to get a sketch of it on previous versions:
![image](https://user-images.githubusercontent.com/18099310/141317845-8d0dad43-0673-4c5f-8215-e40c82e75da6.png)
The paths didn't manage to track all of the ways properly, but it seems to have a single steady state, then a region with 5, then a region with 3, then 5 and then 1 again. I think there are 2 branch points and 4 fold points.

I managed to get that sketch using deflated continuation, but I think the code don't work anymore, and it looked kind of weird, so I figured maybe I should try using the bifurcation diagram feature (https://rveltz.github.io/BifurcationKit.jl/dev/BifurcationDiagram/) which computes it recursively (but then that might have some problems because there's a cycle). Possibly branch switching is better (https://rveltz.github.io/BifurcationKit.jl/dev/branchswitching/), since I know more or less what to expect.

However, all of the inputs for these methods require the function and 3 derivatives. Because I get my function via reaction networks I have the function, and the first derivative (the Jacobian, but that is what is being requested, right). Is it possible to perform these with only those two inputs (I tried, but got some error, but it might be I am making some other input mistake). Is there any disadvantage to not providing 2nd and 3rd derivatives?

**Comment by rveltz** [comment]
> but I think the code don't work anymore, and it looked kind of weird,

Strange, it should not. A look at News.md in BifurcationKit may help you. 

> but then that might have some problems because there's a cycle

Setting a low recursion level (eg 2) would remove the issue. You can then reapply aBD on a specific part of the diagram if you want to refine.

> Because I get my function via reaction networks I have the function, and the first derivative

Can't you try like in this [issue](https://github.com/rveltz/BifurcationKit.jl/issues/45) and use `jet_smooth = BK.getJet(F_smooth, J_smooth; matrixfree=false)`?

> Is it possible to perform these with only those two inputs?

3 answers
- yes by using https://github.com/JuliaDiff/FiniteDifferences.jl and give it to bifurcationKit
- yes deflated continuation
- Modelling toolkit and symbolic derivatives?

The derivative are used to compute the reduced equation (e.g normal form) and find a guess on the bifurcating branch. Without it and without deflated continuation, you must do branching manually :(

I also have an improved version of deflated continuation which "fill the gaps" in your figure. However, it is a bit stalled for now as my focus has shifted before I get back to it.

But frankly, for ODEs, I would be surprised if you can't use AD and that would be worth its own issue.

**Comment by TorkelE** [comment]
Thanks for the quick reply! Quite a lot of information, and https://github.com/rveltz/BifurcationKit.jl/issues/45 seems like a good read. Hopefully, this should be enough for me to go through the options and figure it out, well note you when I'm done. Thanks again :)

**Comment by TorkelE** [comment]
You are right, using `getJet` is the way to go, and it works. Thanks!
