### ISSUE TITLE
bifurcationdiagram() function fails to track new branches in pitchfork bifurcation

### ISSUE THREAD

**Issue by TorkelE** [rveltz/BifurcationKit.jl#47]
Hello,
I try to compute a bifurcation diagram using the `bifurcationdiagram` function. The system is a 2 variable ODE originating from a biochemical reaction network. This is the example:
```julia
# Fetch packages.
using BifurcationKit
using Catalyst
using OrdinaryDiffEq
using Plots
using Setfield

# Declare our model.
hillAR(x1,x2,v,K,n) = (v*x1^n)/(x1^n+x2^n+K^n)
ss_network = @reaction_network begin
    v0+hillAR(S*X,D*Y,v,K,n), ∅ → X
    v0+hillAR(S*Y,D*X,v,K,n), ∅ → Y
    1,(X,Y) → ∅
end S D v0 v n K;

# Generate system functions.
odefun = ODEFunction(convert(ODESystem,rn),jac=true)
F = (u,p) -> odefun(u,p,0)      
J = (u,p) -> odefun.jac(u,p,0);
jet = BifurcationKit.getJet(F, J; matrixfree=false)

# Select parameters
params_in = [1.0,0.5,0.1,1.0,2,0.5]; 
p_idx = 1; 
p_span = (0.1,2.5)
params = setindex!(copy(params_in),p_span[1],p_idx);

# Set options.
dsmax = params[p_idx]/500
dsmin = min(params[p_idx]/10000,1e-4)
ds = sqrt(dsmax*dsmin);
opts_br = ContinuationPar(pMin = p_span[1], pMax = p_span[2], dsmax = dsmax, dsmin = dsmin, ds=ds, maxSteps = 1000000,
    detectBifurcation = 3,
    nInversion = 6, maxBisectionSteps = 25,
    nev = 3);

# Compute diagram.
bif = bifurcationdiagram(jet..., u0, params, (@lens _[p_idx]), 3,
    (x,p,level)->setproperties(opts_br); 
    tangentAlgo = NaturalPred(),
    recordFromSolution=(x, p) -> x[v_idx], verbosity = 0, plot=false);

# Plot the diagram.
plot(bif)
```
Now, this produces the print:
```
##################################################
---> Automatic computation of bifurcation diagram

────────────────────────────────────────────────────────────────────────────────
--> New branch, level = 2, dim(Kernel) = 1, code = 0, from bp #1 at p = 0.858837922561846, type = bp
- #  1,    bp at p ≈ +0.85883792 ∈ (+0.85883753, +0.85883792), |δp|=4e-07, [converged], δ = ( 1,  0), step = 3797, eigenelements in eig[3798], ind_ev =   1
----> From Pitchfork
- #  1,    bp at p ≈ +0.85883792 ∈ (+0.85883753, +0.85883792), |δp|=4e-07, [converged], δ = ( 1,  0), step = 3797, eigenelements in eig[3798], ind_ev =   1
────────────────────────────────────────────────────────────────────────────────
--> New branch, level = 2, dim(Kernel) = 1, code = 0, from bp #2 at p = 1.0061644362337048, type = bp
- #  2,    bp at p ≈ +1.00616444 ∈ (+1.00616439, +1.00616444), |δp|=5e-08, [converged], δ = (-1,  0), step = 4534, eigenelements in eig[4535], ind_ev =   1
----> From Pitchfork
- #  2,    bp at p ≈ +1.00616444 ∈ (+1.00616439, +1.00616444), |δp|=5e-08, [converged], δ = (-1,  0), step = 4534, eigenelements in eig[4535], ind_ev =   1
```
and the plot:
![image](https://user-images.githubusercontent.com/18099310/141337862-bc1afacd-e97d-436c-97d7-03b77d791454.png)

However, the bifurcation diagram should look more like this:
![image](https://user-images.githubusercontent.com/18099310/141337969-a50446b1-0052-4370-a488-dbaea9668023.png)
Basically, in the two branch (pitchfork?) points, two branches go out, which (via two fold points) later connect to the other pitchfork bifurcation.

The code above generates a single branch, with 4 children, if I plot each
```julia
plot(plot(bif.γ),plot(bif.child[1].γ),plot(bif.child[2].γ),plot(bif.child[3].γ),plot(bif.child[4].γ),size=(1200,600))
```
I get
![image](https://user-images.githubusercontent.com/18099310/141339276-e4a3fcbb-6a20-4787-9565-fa47a01baacd.png)

this makes it seem like the solver detects that there are two branches going out from each pitchfork point. However, when it tracks these two, it simply follows the original path back/forward towards the end, creating some overlap.

I have tried changing options in `(x,p,level)->setproperties(opts_br)`, using various combinations of what is used in the first example at https://bifurcationkit.github.io/BifurcationKitDocs.jl/dev/BifurcationDiagram/, however, with no luck. I also tried removing `tangentAlgo = NaturalPred()`, but for large `level` Julia crashes, and for smaller when I try to print the bifurcation diagram I get no output.

I have also tried making the sign of `ds` iterate with the level, using 
```julia
(x,p,level)->setproperties(opts_br;ds=-ds*(-1)^level)
```
but it didn't work.

Is it just that I am missing some option to make it properly detect the branches, or is there some other problem?

**Comment by rveltz** [comment]
sorry, your code is not working.

**Comment by TorkelE** [comment]
Thank you.

Yes, switching `NaturalPred()` to `SecantPred()` improved things a lot. I also noted that the 2nd level of branches reached maxiter, so limiting that (and increasing `dsmax` improved things.

Thanks a lot.
