### ISSUE TITLE
Change from DiffEqBase to SciMLBase

### ISSUE THREAD

**Issue by ChrisRackauckas** [rveltz/BifurcationKit.jl#49]
DiffEqBase is the lowest common denominator for the DiffEq packages, not necessarily the whole SciML ecosystem, and so it has a lot DiffEq dependencies. These are generally not required by downstream packages. If what you're looking for is a way to define problems without having most dependencies, we recommend you use SciMLBase as the dependency since everything like ODEProblem, SteadyStateProblem, etc. is defined there. We basically recommend depending on SciMLBase for problem definitions, and solver packages for specific solvers, but generally most non-SciML packages should not be depending on DiffEqBase directly (given the split of SciMLBase in 2021)

For more details see: https://diffeq.sciml.ai/stable/features/low_dep/ and https://discourse.julialang.org/t/psa-the-right-dependency-to-reduce-from-differentialequations-jl/72757

Let me know if you need any help updating this, though for almost all dependents here it should be a trivial name change as you're actually using pieces from SciMLBase.

**Comment by rveltz** [comment]
I will try to depend only on SciMLBase. Thank you for the hint.

**Comment by rveltz** [comment]
I need `VectorContinuousCallback` for Poincare Shooting. See [here](https://github.com/rveltz/BifurcationKit.jl/blob/master/src/periodicorbit/ShootingDE.jl#L61).
I am not sure I can get away with SciMLBase. Or Maybe, I use `Requires.jl` on DE?

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/DiffEqBase.jl/pull/721

**Comment by ChrisRackauckas** [comment]
Require SciMLBase v1.21 after that is released.

**Comment by rveltz** [comment]
Nicceeee! Thank you :)

**Comment by rveltz** [comment]
Is it possible to have (L926 in DiffEqBase v6.76.0)

```
  max_len_cb = DiffEqBase.max_vector_callback_length_int(callbacks_internal)
```

being `-1`??

**Comment by ChrisRackauckas** [comment]
That shouldn't be possible.

**Comment by rveltz** [comment]
By updating to OrdinaryDiffEq = "5.67", I dont get the error anymore
