### ISSUE TITLE
Weird bifurcation diagram produced

### ISSUE THREAD

**Issue by TorkelE** [rveltz/BifurcationKit.jl#50]
I am using the `bifurcationdiagram` on a simple function (with a bistable region. However, there is a weird jump in the diagram (best just seen in the image at the end). It seems something weird gets mixed up.

```julia
# Fetch packages
using ModelingToolkit, OrdinaryDiffEq, BifurcationKit, Plots, Setfield, LinearAlgebra

# Declare model.
@parameters t s d T v0 n
@variables X(t) A1(t) A2(t) A3(t)
D = Differential(t)

eqs = [D(X) ~ v0 + ((s*X)^n)/((s*X)^n + (d*A3)^n + 1) - X,
       D(A1) ~ (X-A1)/T,
       D(A2) ~ (A1-A2)/T,
       D(A3) ~ (A2-A3)/T]

@named sys = ODESystem(eqs);

# Prepares input 
params_input = [0.25,1.0,0.1,3,0.1]  # Order is "d,s,v0,n,T", check in "sys.ps". Should be fine.
p_span = (1.,4.);
#odefun = ODEFunction(convert(ODESystem,network),jac=true)
odefun = ODEFunction(sys,jac=true)
F = (u,p) -> odefun(u,p,0)      
J = (u,p) -> odefun.jac(u,p,0)
jet = BifurcationKit.getJet(F, J; matrixfree=false)

u0 = solve(ODEProblem(sys,rand(length(sys.states)),(0.,100.0),params_input),Rosenbrock23()).u[end];

# Sets options
dsmax = 1e-2
dsmin = 1e-5
ds = sqrt(dsmax*dsmin);
maxSteps = 10000
opts_br = ContinuationPar(pMin = p_span[1], pMax = p_span[2], dsmax = dsmax, dsmin = dsmin, ds=ds, maxSteps=maxSteps,
detectBifurcation = 3, nInversion = 6, maxBisectionSteps = 25,nev = 4);

# Calculates the diagram.
bif = bifurcationdiagram(jet..., u0, params_input, (@lens _[2]), 2,
    (x,p,level)->setproperties(opts_br);
    tangentAlgo = SecantPred(),
    recordFromSolution=(x, p) -> x[1], verbosity = 0, plot=false);

# Plots the diagram.
plot(bif)
```
![image](https://user-images.githubusercontent.com/18099310/145612624-3a27b466-a67b-4add-8ea2-99e049104ba4.png)

This is my `Pkg.status()`
```
  [0f109fa4] BifurcationKit v0.1.8
  [479239e8] Catalyst v10.2.0 `~/.julia/dev/Catalyst`
  [c894b116] DiffEqJump v8.0.0
  [0c46a032] DifferentialEquations v6.20.0
  [961ee093] ModelingToolkit v7.1.3
  [1dea7af3] OrdinaryDiffEq v5.69.0
  [91a5bcdd] Plots v1.24.3
  [f27b6e38] Polynomials v2.0.17
  [295af30f] Revise v3.2.0
  [2913bbd2] StatsBase v0.33.13
  [f3b207a7] StatsPlots v0.14.29
  [789caeaf] StochasticDiffEq v6.41.0
```

**Comment by rveltz** [comment]
Strange, I dont get that. First I get `u0=[3.24,3.24,3.24,3.24]`.

Can you try a better predictor like `BorderedPred()` please?
`dsmax` is quite small

**Comment by TorkelE** [comment]
I suspect that (i.e. you getting a different `u0`) might have something to do with ModelingToolkit stuff moving away from using "order" in parameters. I.e. before I would typically say that my model had the parameters `[k1,k2,k3]`, and I would pass their values as `[1.0,2.0,3.0]`. However, I think in the future the plan is that parameters generally should be passed as `[k1=>1.0,k2=>2.0,k3=>3.0] (never mind the exact details, but something along these lines). When we both pass `[0.25,1.0,0.1,3,0.1]` we are maybe having different orders of the parameters, and are actually using different parameter sets.

Either way, `BorderedPred()` worked! Thanks a lot :)
Is there a good summary of the various `tangentAlgo` arguments, it feels like I have made errors here before. There we some mention here https://bifurcationkit.github.io/BifurcationKitDocs.jl/dev/library/#BifurcationKit.continuation but no proper description of the different ones and when to use that I could find.

**Comment by rveltz** [comment]
> Is there a good summary of the various tangentAlgo arguments, it feels like I have made errors here before.

I would say: https://bifurcationkit.github.io/BifurcationKitDocs.jl/dev/Predictors/ but no docs is perfect and certainly users are great help for improving them.

I am (slowly) trying to get away from the type of docs you mention, there are too many `continuation` methods. I'd look at Functionalities menu.

Also, your system is small and if the newton iteration are large enough, the continuation will jump instead of having a failed continuation step (which is totally fine because it then adapts).

**Comment by rveltz** [comment]
I think we might need a sub package like `ODEBifucationKit.jl` where all the calls are overloaded with default options tailored for ODE (like small `maxIter`, use of `MatrixBLS()`, etc

**Comment by TorkelE** [comment]
Yes, that would probably make sense, especially once it is certain how this parameter order-thing will work. I'm happy to help (after January, at which point I hand in my thesis...)

**Comment by rveltz** [comment]
oh! good luck with this!
