### ISSUE TITLE
Tutorial for finding periodic orbits of non-spatial systems

### ISSUE THREAD

**Issue by TorkelE** [rveltz/BifurcationKit.jl#58]
I have a couple of systems for which I have done bifurcation diagrams using bifurcation kit, and there are some Hopf bifurcation points. I would like to also plot the periodic orbits for these. When I check the tutorials, they all seem to be for spatial systems. Is there some tutorial or example for non-spatial systems, or is it plausible to make it work for the non-spatial case by looking at these?

**Comment by rveltz** [comment]
Sure ! Look at the ode examples.

Contact me if you struggled

Best

Le 5 juin 2022 00:05:57 Torkel ***@***.***> a écrit :
>
> I have a couple of systems for which I have done bifurcation diagrams using 
> bifurcation kit, and there are some Hopf bifurcation points. I would like 
> to also plot the periodic orbits for these. When I check the tutorials, 
> they all seem to be for spatial systems. Is there some tutorial or example 
> for non-spatial systems, or is it plausible to make it work for the 
> non-spatial case by looking at these?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message 
> ID: ***@***.***>


Envoyé avec Aqua Mail pour Android
https://www.aqua-mail.com

**Comment by TorkelE** [comment]
Yes, those seems to be the ones, thanks :)
