### ISSUE TITLE
Interpreting a bifurcation diagram (that takes a long time to computer)

### ISSUE THREAD

**Issue by TorkelE** [rveltz/BifurcationKit.jl#62]
Hi again,

I have been able to compute the periodic orbits for a model I am working on, however, there are some things going on in the diagram which I do not understand.

I fetch the required stuff:
```julia
using Revise, ForwardDiff, Parameters, Setfield, Plots, LinearAlgebra
using BifurcationKit
using Catalyst, DifferentialEquations
const BK = BifurcationKit

norminf(x) = norm(x, Inf);
```
Then compute the bifurcation diagram, without tracking the periodic orbits:
```julia
function model(dz, z, p, t)    
    S,D,τ,v0,n = p
    s,A1,A2,A3 = z
    dz[1] = v0 + (S*s)^n / ((S*s)^n + (D*A3)^n + 1) - s
    dz[2] = (s-A1)/τ
    dz[3] = (A1-A2)/τ
    dz[4] = (A2-A3)/τ
    dz
end

F = (z,p) -> model(similar(z), z, p, 0) 
J = (z,p) -> ForwardDiff.jacobian(x -> F(x,p), z)
jet = BK.getJet(F, J);

# parameter values
ps = [1.,5.,10.0,0.1,3,0.]
p_span = (1.,12.)

# initial condition
z0 = [0.1, 0.1, 0.1, 0.1]; 

# continuation options
opts_br = ContinuationPar(pMin = p_span[1], pMax = p_span[2], dsmax=(p_span[2]-p_span[1])/200.0,dsmin=(p_span[2]-p_span[1])/100000,maxSteps=100000, ds = sqrt(((p_span[2]-p_span[1])/100000)*((p_span[2]-p_span[1])/200.0)),
                detectBifurcation = 3, nInversion = 6, maxBisectionSteps = 25,nev = 20);

# Calculates the diagram.
br, = continuation(F,J, z0, ps,  (@lens _[1]), opts_br;
    recordFromSolution=(x, p) -> x[1],
    tangentAlgo = BorderedPred(),
    plot = false, verbosity = 0, normC = norminf)

scene = plot(br, plotfold=false, markersize=3, legend=:topleft)
```
![image](https://user-images.githubusercontent.com/18099310/174326752-6f02d946-e3ea-4323-8e39-7b42b4054601.png)
Here the system has a region of instability, that I have previously associated with a limit cycle appearing.

Next, I compute and plot the periodic orbit:
```julia
# newton parameters
optn_po = NewtonPar(verbose = false, tol = 1e-8,  maxIter = 10);

# continuation parameters
opts_po_cont = ContinuationPar(pMin = 1.0, pMax = 12.0, ds = -0.04, dsmax = 0.05,     ### Changed pMin and pMax ###
	maxSteps = 100000, newtonOptions = (@set optn_po.tol = 1e-7),
	nev = 4, precisionStability = 1e-8, detectBifurcation = 3, plotEveryStep = 10, saveSolEveryStep=1)

# arguments for periodic orbits
args_po = (	recordFromSolution = (x, p) -> (xtt = BK.getPeriodicOrbit(p.prob, x, p.p);
		return (max = maximum(xtt.u[1,:]),
				min = minimum(xtt.u[1,:]),
				period = x[end])),
	plotSolution = (x, p; k...) -> begin
		xtt = BK.getPeriodicOrbit(p.prob, x, p.p)
		plot!(xtt.t, xtt.u[1,:]; label = "s", k...)
		plot!(br,subplot=1, putbifptlegend = false)
		end,
	normC = norminf)

Mt = 200 # number of time sections
@time br_potrap, utrap = continuation(jet...,
	# we want to branch form the 4th bif. point
	br, 1, opts_po_cont,                 ### Now uses 1st bp ###
	# we want to use the Trapeze method to locate PO
	PeriodicOrbitTrapProblem(M = Mt);
	# this jacobian is specific to ODEs
	# it is computed using AD and
	# updated inplace
	linearPO = :Dense,
	# regular continuation options
	verbosity = 0,	plot = false, δp = 0.005, 
	args_po...)

scene = plot(br, br_potrap, markersize = 3)
plot!(scene, br_potrap.param, br_potrap.min, label = "")
```
![image](https://user-images.githubusercontent.com/18099310/174341153-1fce73a5-b943-47ae-b775-5602de7aa857.png)

I also get a large number of 
```

┌ Warning: Error in eigenvalues computation. It seems that an eigenvalue is missing, probably conj(λ) for some already computed eigenvalue λ. This makes the identification (but not the detection) of bifurcation points erroneous. You should increase the number of requested eigenvalues `nev`.
└ @ BifurcationKit /home/torkelloman/.julia/dev/BifurcationKit/src/Bifurcations.jl:106
┌ Warning: Error in eigenvalues computation. It seems that an eigenvalue is missing, probably conj(λ) for some already computed eigenvalue λ. This makes the identification (but not the detection) of bifurcation points erroneous. You should increase the number of requested eigenvalues `nev`.
└ @ BifurcationKit /home/torkelloman/.julia/dev/BifurcationKit/src/Bifurcations.jl:106
┌ Warning: Error in eigenvalues computation. It seems that an eigenvalue is missing, probably conj(λ) for some already computed eigenvalue λ. This makes the identification (but not the detection) of bifurcation points erroneous. You should increase the number of requested eigenvalues `nev`.
└ @ BifurcationKit /home/torkelloman/.julia/dev/BifurcationKit/src/Bifurcations.jl:106
┌ Warning: Error in eigenvalues computation. It seems that an eigenvalue is missing, probably conj(λ) for some already computed eigenvalue λ. This makes the identification (but not the detection) of bifurcation points erroneous. You should increase the number of requested eigenvalues `nev`.
└ @ BifurcationKit /home/torkelloman/.julia/dev/BifurcationKit/src/Bifurcations.jl:106
```
output.

- First I note that this take well over an hour in time, is this expected (I am rerunning everything right now to check, but it drags on a lot)? It feels very long. If I remember right, is that a canard explosion going on at the beginning of the diagram (you showed me these before), and is that related to things taking time?
- All the `Error in eigenvalues computation.`. This doesn't seem to cause any problem, but I was setting `nev=4`, and have a 4 variable model , so thought that it wouldn't make sense to increase `nev`?
- Next, the periodic orbits don't seem to be connecting to the 2nd Hopf bifurcation, which I expected. What is going on here? In addition, for a small region here the fixed point seems to be stable, but we still have a limit cycle (I also confirmed this through simulation). Is this a thing that can happen (I have never encountered it before)?

**Comment by TorkelE** [comment]
Thanks a lot! Yes, I will work with this. 

Regarding the runtime I first tried:
```julia
plot(br_potrap)
```
but that just returned the periodic orbit (max value):
![image](https://user-images.githubusercontent.com/18099310/174345279-a5c32419-6f68-4948-8e7f-fa60665e0c6c.png)

Extracting the values though:
```julia
plot(map(i -> br_potrap.param[i], 1:length(br_potrap)))
```
gives something:
![image](https://user-images.githubusercontent.com/18099310/174345232-05134d31-a212-4dc7-8519-096568e11bfb.png)
but I am not sure of what.

But maybe shooting or collocation is better here anyway?

**Comment by rveltz** [comment]
see it come back to p=3. Please try this before

```
updateSectionEveryStep = 1,
```

**Comment by TorkelE** [comment]
Thanks a lot, really helpful!

**Comment by rveltz** [comment]
did you manage?

**Comment by TorkelE** [comment]
Yes, adding the `` option made the run time manageable (5 minutes).

I was also able to adapt the shooting example from the tutorial and use it:
![image](https://user-images.githubusercontent.com/18099310/174387361-7c480629-b8f9-4ef3-b37c-22d1ea876f2b.png)
I am still a bit unsure what it means that for some parameter values, the periodic orbit has two max (and min) values. Are there two limit cycles?
(I am happy to try and figure this out as an own exercise though, thanks for all the help!)

**Comment by rveltz** [comment]
> I am still a bit unsure what it means that for some parameter values, the periodic orbit has two max (and min) values. Are there two limit cycles?

yes!

**Comment by TorkelE** [comment]
> Also, if you look at br_potrap.eig and look at the eigenvalues, you will notice that one is always very close to zero: in theory it should be zero. If you then change accordingly `ContinuationPar.precisionStability', it will improve the stability computation.

Useful to know!

> which option?

I used this:
```julia
probsh = ODEProblem(odefun, [0.1, 0.10000000513601319, 0.10000014659364033, 0.10000195284745092], (0., 1000.), model.p_vals; abstol = 1e-10, reltol = 1e-7)
optn_po = NewtonPar(verbose = true, tol = 1e-8, maxIter = 25)
opts_po_cont = ContinuationPar(dsmax = 0.01, ds= -0.001, dsmin = 1e-4, pMin=1.0,pMax=12.0,maxSteps = 1300, newtonOptions = optn_po, precisionStability = 1e-5, detectBifurcation = 3, plotEveryStep = 10, saveSolEveryStep = 1, nInversion = 6, nev = 4)

function plotPO(x, p; k...)
	xtt = BifurcationKit.getPeriodicOrbit(p.prob, x, p.p)
	plot!(xtt.t, xtt[1,:]; markersize = 2, k...)
end
function recordPO(x, p)
	xtt = BifurcationKit.getPeriodicOrbit(p.prob, x, p.p)
	period = BifurcationKit.getPeriod(p.prob, x, p.p)
	return (max = maximum(xtt[1,:]), min = minimum(xtt[1,:]), period = period)
end

br_po, = continuation(
	jet...,  bif.bk_output, 1, opts_po_cont,
	# parallel shooting functional with 10 sections
	ShootingProblem(15, probsh, Rodas4P(); parallel = true, reltol = 1e-9);
	# first parameter value on the branch
	δp = 0.0051,
	# method for solving newton linear system
	# specific to ODE
	jacobianPO = :autodiffDense,
	verbosity = 3,	plot = true,
	recordFromSolution = recordPO,
	plot=false,
	# limit the residual, useful to help DifferentialEquations
	callbackN = BifurcationKit.cbMaxNorm(10),
	normC = x->norm(x, Inf))
```

> yes!

This is exciting! Also, these coexist with a stable fixed point as well? I tried a lot of simulations, and can only find the "outer" periodic orbit and the fixed point. Does my impression that we have a stable fixed point and a stable periodic orbit, separated by an "unstable" periodic orbit make sense?

**Comment by rveltz** [comment]
interesting that you dont need `updateSectionEveryStep`.

> Also, these coexist with a stable fixed point as well?

yes

> Does my impression that we have a stable fixed point and a stable periodic orbit, separated by an "unstable" periodic orbit make sense

no because the system is 4d, it would make sense in 2d

**Comment by TorkelE** [comment]
Ok, I think I understand (a bit), yeah, I am probably very 2d centric (the original model was 2d, but then I added 2 more intermediary variables to modify the delay).

So we cannot really say whenever the POs are stable or unstable with just pure deduction like that? Or all POs we compute this way are stable?

**Comment by rveltz** [comment]
> So we cannot really say whenever the POs are stable or unstable with just pure deduction like that? Or all POs we compute this way are stable?

i dont get it, you just computed their stability with BK

**Comment by TorkelE** [comment]
OK, yes, I misunderstood, I didn't realise that BK did the stability of the periodic orbits as well. I tried a lot of simulations in the region with the two periodic orbits, and only managed to end up in one of them, so I erroneously assumed the other one was unstable.
